-- FalconShield AI Credit Card Fraud Detection Database Schema
-- Compatible with PostgreSQL 13+

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'FRAUD_ANALYST', -- ADMIN, FRAUD_ANALYST, CUSTOMER_SUPPORT
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers (
    id VARCHAR(36) PRIMARY KEY,
    customerName VARCHAR(100) NOT NULL,
    cardNumber VARCHAR(20) NOT NULL,
    riskScore FLOAT DEFAULT 0.0,
    location VARCHAR(100) NOT NULL,
    totalSpent DECIMAL(12, 2) DEFAULT 0.00,
    fraudCount INT DEFAULT 0,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    id VARCHAR(36) PRIMARY KEY,
    customerId VARCHAR(36) NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    amount DECIMAL(10, 2) NOT NULL,
    merchant VARCHAR(150) NOT NULL,
    merchantCategory VARCHAR(50) NOT NULL,
    transactionDate TIMESTAMP WITH TIME ZONE NOT NULL,
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    deviceType VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'APPROVED', -- APPROVED, FLAGGED, BLOCKED
    fraudScore FLOAT NOT NULL DEFAULT 0.0,
    prediction VARCHAR(30) NOT NULL DEFAULT 'Legitimate', -- Legitimate, Fraudulent
    riskCategory VARCHAR(30) NOT NULL DEFAULT 'Low Risk', -- Low Risk, Medium Risk, High Risk, Critical Risk
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_alerts (
    id VARCHAR(36) PRIMARY KEY,
    transactionId VARCHAR(36) NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
    severity VARCHAR(30) NOT NULL DEFAULT 'MEDIUM', -- LOW, MEDIUM, HIGH, CRITICAL
    assignedTo VARCHAR(100),
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN', -- OPEN, UNDER_INVESTIGATION, RESOLVED, FALSE_POSITIVE
    notes TEXT,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id VARCHAR(36) PRIMARY KEY,
    userId VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL,
    userName VARCHAR(100) NOT NULL,
    action VARCHAR(100) NOT NULL,
    details TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_rules (
    id VARCHAR(36) PRIMARY KEY,
    ruleName VARCHAR(100) NOT NULL,
    conditionType VARCHAR(50) NOT NULL, -- MAX_AMOUNT, VELOCITY_LIMIT, HIGH_RISK_COUNTRY, NIGHT_TRANSACTION
    threshold VARCHAR(100) NOT NULL,
    action VARCHAR(50) NOT NULL, -- BLOCK, FLAG, ALERT
    isEnabled BOOLEAN DEFAULT TRUE,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
